FROM golang:1.22

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

ARG AWS_ACCESS_KEY_ID
ENV AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID

ARG AWS_SECRET_ACCESS_KEY
ENV AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY

ARG AWS_SESSION_TOKEN
ENV AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN

ARG AWS_PRODUCTION_PAYMENT_SQS_URL
ENV AWS_PRODUCTION_PAYMENT_SQS_URL=$AWS_PRODUCTION_PAYMENT_SQS_URL

ARG AWS_PRODUCTION_UPDATE_SQS_URL
ENV AWS_PRODUCTION_UPDATE_SQS_URL=$AWS_PRODUCTION_UPDATE_SQS_URL

ARG AWS_REGION
ENV AWS_REGION=$AWS_REGION

ARG PORT
ENV PORT=$PORT

ARG MONGO_URL
ENV MONGO_URL=$MONGO_URL

RUN go build .

EXPOSE 8080

# ENV ENV_FILE_LOCATION=/app/.env

CMD ["./fiap-fast-food-ms-producao"]
